name: e_commerce_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  dots_indicator: ^4.0.1
  firebase_core: ^3.12.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.5
  flutter_screenutil: ^5.9.3
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.1
  google_nav_bar: ^5.0.7
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/core/utils
  filename: assets.dart
  field_prefix: null
