// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyWkR4GflAllC36znlApVuZfY3-BTVfLQ',
    appId: '1:427926175694:web:2000c95dccc0ed01c2759f',
    messagingSenderId: '427926175694',
    projectId: 'easy-shop-ec4f3',
    authDomain: 'easy-shop-ec4f3.firebaseapp.com',
    storageBucket: 'easy-shop-ec4f3.firebasestorage.app',
    measurementId: 'G-P8TESRYTMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAAJQ-jifzhORte-1giNX3D_tIDxFlhio',
    appId: '1:427926175694:android:ede52e21d25b8026c2759f',
    messagingSenderId: '427926175694',
    projectId: 'easy-shop-ec4f3',
    storageBucket: 'easy-shop-ec4f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PGj6P-pFrx3AV9PW6upn2bu18xnLxZI',
    appId: '1:427926175694:ios:35c94d1bca92d300c2759f',
    messagingSenderId: '427926175694',
    projectId: 'easy-shop-ec4f3',
    storageBucket: 'easy-shop-ec4f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PGj6P-pFrx3AV9PW6upn2bu18xnLxZI',
    appId: '1:427926175694:ios:35c94d1bca92d300c2759f',
    messagingSenderId: '427926175694',
    projectId: 'easy-shop-ec4f3',
    storageBucket: 'easy-shop-ec4f3.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyWkR4GflAllC36znlApVuZfY3-BTVfLQ',
    appId: '1:427926175694:web:2a567908a5547b51c2759f',
    messagingSenderId: '427926175694',
    projectId: 'easy-shop-ec4f3',
    authDomain: 'easy-shop-ec4f3.firebaseapp.com',
    storageBucket: 'easy-shop-ec4f3.firebasestorage.app',
    measurementId: 'G-0RJCE4TZJJ',
  );
}
